import Foundation

nonisolated enum ModelPricingStatus: String, Codable {
    case estimated, subscription, free, pending
    var title: String {
        switch self {
        case .estimated: return "API equivalent"
        case .subscription: return "Subscription"
        case .free: return "Free API model"
        case .pending: return "Price pending"
        }
    }
}

nonisolated struct ModelRate: Identifiable, Decodable {
    var provider: String
    var model: String
    var input: Double
    var output: Double
    var cached: Double?
    var threshold: Double?
    var longInput: Double?
    var longOutput: Double?
    var longCached: Double?
    var url: String
    var status: ModelPricingStatus
    var notes: String?
    var context: Int?
    var id: String { "\(provider)/\(model)" }
    var isLocalInference: Bool { url.hasPrefix("local://") }

    /// Exact API-equivalent for one call, or nil when its split or tier is unknown.
    func estimate(_ tokens: ModelTokenCounts) -> Double? {
        guard let cost = costRange(tokens, calls: 1), cost.exact else { return nil }
        return cost.low
    }

    /// API-equivalent bounds for one record. A single call's prompt selects its tier;
    /// several (or an unreported number of) calls prove only the base tier, and only
    /// while their combined prompt stays below the threshold. Unsplit tokens span the
    /// cheapest to the dearest category. The bounds meet whenever the record is exact.
    func costRange(_ tokens: ModelTokenCounts, calls: Int) -> ModelCostRange? {
        guard tokens.isValid, !isLocalInference, status == .estimated || status == .free else { return nil }
        let base = Tier(input: input, cached: cached ?? input, output: output)
        var tiers = [base]
        if let threshold {
            let longInputRate = longInput ?? input
            let long = Tier(input: longInputRate, cached: longCached ?? cached ?? longInputRate, output: longOutput ?? output)
            if calls == 1 && tokens.prompt >= threshold { tiers = [long] }
            else if tokens.prompt + tokens.unsplit >= threshold { tiers = [base, long] }
        }
        if tiers.count == 1 && tokens.unsplit == 0 {
            let cost = tiers[0].cost(tokens)
            return ModelCostRange(low: cost, high: cost, exact: true)
        }
        let floor = Tier(input: tiers.map(\.input).min()!, cached: tiers.map(\.cached).min()!, output: tiers.map(\.output).min()!)
        let ceiling = Tier(input: tiers.map(\.input).max()!, cached: tiers.map(\.cached).max()!, output: tiers.map(\.output).max()!)
        let low = floor.cost(tokens) + tokens.unsplit * min(floor.input, floor.cached, floor.output) / 1_000_000
        let high = ceiling.cost(tokens) + tokens.unsplit * max(ceiling.input, ceiling.cached, ceiling.output) / 1_000_000
        return ModelCostRange(low: low, high: high, exact: low == high)
    }

    private struct Tier {
        var input: Double, cached: Double, output: Double
        // TaskWraith's API-equivalent convention: cache creation uses input rate.
        func cost(_ tokens: ModelTokenCounts) -> Double {
            ((tokens.input + tokens.cacheWrite) * input + tokens.cacheRead * cached + tokens.output * output) / 1_000_000
        }
    }
}

/// An exact API-equivalent has equal bounds; a range is never presented as one figure.
nonisolated struct ModelCostRange: Equatable, Sendable {
    var low: Double
    var high: Double
    var exact: Bool
}

nonisolated enum ModelRateCatalog {
    static let version = "2026-09-24"
    static let provenance = "TaskWraith ProviderRateService · 2026-09-24"
    /// Content fingerprint of every row and mapping, so a rate edit without a date
    /// bump still invalidates cached rollups and republishes the archive.
    static let fingerprint = fingerprint(of: rates)
    static func fingerprint(of rates: [ModelRate]) -> String {
        var lines = rates.map { rate in
            [rate.provider, rate.model, "\(rate.input)", "\(rate.output)", "\(rate.cached ?? -1)", "\(rate.threshold ?? -1)",
             "\(rate.longInput ?? -1)", "\(rate.longOutput ?? -1)", "\(rate.longCached ?? -1)", rate.status.rawValue, rate.url]
                .joined(separator: "|")
        }
        lines += routeAliases.map { "alias|\($0.key)|\($0.value.0)|\($0.value.1)" }.sorted()
        lines += nativeAliases.map { "native|\($0.key)|\($0.value)" }.sorted()
        lines += routedProviders.map { "route|\($0.key)|\($0.value)" }.sorted()
        var hash: UInt64 = 0xcbf29ce484222325
        for byte in lines.joined(separator: "\n").utf8 { hash = (hash ^ UInt64(byte)) &* 0x100000001b3 }
        return String(hash, radix: 16)
    }
    /// Stored with archives and compared on refresh.
    static var revision: String { "\(version)#\(fingerprint)" }
    private static let rateIndices = Dictionary(rates.enumerated().map {
        ("\($0.element.provider)/\($0.element.model)", $0.offset)
    }, uniquingKeysWith: { first, _ in first })
    private static let routeAliases: [String: (String, String)] = [
        "claude/fable": ("claude", "claude-fable-5-1"),
        "claude/opus": ("claude", "claude-opus-5-5"),
        "claude/sonnet": ("claude", "claude-sonnet-5"),
        "kimi/kimi-for-coding": ("kimi", "kimi-k2.8-preview"),
        "kimi/kimi-for-coding-highspeed": ("kimi", "kimi-k2.7-code-highspeed"),
        "kimi/k3": ("kimi", "kimi-k3")
    ]
    /// Exact wire ids a provider's own CLI logs. The Grok Build CLI writes `-build`
    /// ids for the models TaskWraith records, for the same runs, as grok-4.6/4.7;
    /// Kimi Code logs its route aliases, mapped as TaskWraith's `kimiCostRateModel`.
    private static let nativeAliases: [String: String] = [
        "grok/grok-4.6-build": "grok-4.6",
        "grok/grok-4.7-build": "grok-4.7",
        "kimi/kimi-code/kimi-for-coding": "kimi-k2.8-preview",
        "kimi/kimi-code/kimi-for-coding-highspeed": "kimi-k2.7-code-highspeed",
        "kimi/kimi-code/k3": "kimi-k3",
        "kimi/kimi-code/k3-256k": "kimi-k3-256k"
    ]
    private static let routedProviders = [
        "codex": "codex", "openai": "codex", "claude": "claude", "anthropic": "claude",
        "grok": "grok", "xai": "grok", "cursor": "cursor", "gemini": "gemini",
        "google": "gemini", "kimi": "kimi", "moonshot": "kimi", "mistral": "mistral",
        "muse": "muse", "meta": "muse", "antigravity": "antigravity", "ollama": "ollama",
        "pi": "pi"
    ]

    static func resolve(source: String, model: String) -> ModelRate? {
        let name = model.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
        let provider = source == "openaiAPI" || source == "openai" ? "codex" : source
        if let exact = exactRate(provider: provider, model: name) { return exact }
        if let alias = nativeAliases["\(provider)/\(name)"] { return exactRate(provider: provider, model: alias) }

        // TaskWraith also catalogs some routed providers under Pi using the full
        // namespace. Match those exact rows before interpreting the route itself.
        if let routed = exactRate(provider: "pi", model: name) { return routed }
        if let alias = routeAliases[name] { return exactRate(provider: alias.0, model: alias.1) }
        if let alias = nativeAliases[name], let slash = name.firstIndex(of: "/") {
            return exactRate(provider: String(name[..<slash]), model: alias)
        }

        // Only explicit Provider Hub namespaces may redirect pricing away from
        // the host app. An unfamiliar route remains unpriced.
        if let slash = name.firstIndex(of: "/"),
           let routedProvider = routedProviders[String(name[..<slash])] {
            let routedModel = String(name[name.index(after: slash)...])
            return exactRate(provider: routedProvider, model: routedModel)
        }
        return nil
    }

    private static func exactRate(provider: String, model: String) -> ModelRate? {
        if let index = rateIndices["\(provider)/\(model)"] { return rates[index] }
        // Vendor date suffixes preserve a concrete model identity.
        if model.count > 9, model.suffix(9).first == "-", model.suffix(8).allSatisfy(\.isNumber) {
            if let index = rateIndices["\(provider)/\(model.dropLast(9))"] { return rates[index] }
        }
        return nil
    }

    static func estimate(source: String, model: String, tokens: ModelTokenCounts) -> Double? {
        resolve(source: source, model: model)?.estimate(tokens)
    }

    static func costRange(source: String, model: String, tokens: ModelTokenCounts, calls: Int) -> ModelCostRange? {
        resolve(source: source, model: model)?.costRange(tokens, calls: calls)
    }

    // Imported TaskWraith rates; no fallback flags. Exact context rows from 2026-09-24.
    static let rates: [ModelRate] = [
        ModelRate(provider: "grok", model: "grok-4.7", input: 2, output: 6, cached: 0.5, threshold: 200000, longInput: 4, longOutput: 12, longCached: 1, url: "https://docs.x.ai/developers/models/grok-4.6", status: .estimated, notes: "xAI API pricing for Grok 4.7 (500K ctx), carried forward from 4.6. PROJECTED API-equivalent; CLI auth bills via subscription credits.", context: 500000),
        ModelRate(provider: "grok", model: "grok-4.7-fast", input: 2, output: 6, cached: 0.5, threshold: 200000, longInput: 4, longOutput: 12, longCached: 1, url: "https://docs.x.ai/developers/models/grok-4.6", status: .estimated, notes: "xAI API pricing for Grok 4.7 Fast (500K ctx), carried forward from 4.6. PROJECTED API-equivalent; CLI auth bills via subscription credits.", context: 500000),
        ModelRate(provider: "grok", model: "grok-4.6", input: 2, output: 6, cached: 0.5, threshold: 200000, longInput: 4, longOutput: 12, longCached: 1, url: "https://docs.x.ai/developers/models/grok-4.6", status: .estimated, notes: "xAI API pricing for Grok 4.6 (500K ctx). Prompts at or above 200K tokens bill every token at the long-context tier. PROJECTED API-equivalent; CLI auth bills via subscription credits.", context: 500000),
        ModelRate(provider: "grok", model: "grok-4.5", input: 2, output: 6, cached: 0.5, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.x.ai/developers/models/grok-4.5", status: .estimated, notes: "xAI API pricing for Grok 4.5 (500K ctx). PROJECTED API-equivalent; CLI auth bills via subscription credits.", context: 500000),
        ModelRate(provider: "grok", model: "grok-build", input: 2, output: 6, cached: 0.5, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.x.ai/developers/models/grok-4.5", status: .estimated, notes: "Historical Grok Build id now maps to Grok 4.5. PROJECTED API-equivalent; CLI auth bills via subscription credits.", context: 500000),
        ModelRate(provider: "grok", model: "grok-composer-2.5-fast", input: 3, output: 15, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://cursor.com/docs/models/cursor-composer-2-5", status: .estimated, notes: "Composer 2.5 Fast selected through Grok Build CLI. PROJECTED API-equivalent from Cursor Composer pricing; Grok CLI auth bills via SuperGrok/X subscription credits.", context: 200000),
        ModelRate(provider: "grok", model: "grok-4.3", input: 1.25, output: 2.5, cached: 0.2, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.x.ai/developers/pricing", status: .estimated, notes: "xAI API pricing for grok-4.3 (1M ctx). Projected API-equivalent, not actual billing.", context: 1000000),
        ModelRate(provider: "cursor", model: "composer-2.5-fast", input: 3, output: 15, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://cursor.com/docs/models/cursor-composer-2-5", status: .estimated, notes: "Composer 2.5 Fast tier (IDE default). PROJECTED API-equivalent — individual plans draw from the Composer pool, not per-token billing. Used as the fallback rate for unknown Cursor usage rows.", context: 200000),
        ModelRate(provider: "cursor", model: "composer-2.5", input: 0.5, output: 2.5, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://cursor.com/changelog/composer-2-5", status: .estimated, notes: "Composer 2.5 Standard tier. PROJECTED API-equivalent — exact rows should use this lower standard-tier rate instead of the Fast proxy.", context: 200000),
        ModelRate(provider: "cursor", model: "grok-4.6", input: 2, output: 6, cached: 0.5, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://cursor.com/docs/models/grok-4-6", status: .estimated, notes: "Cursor Grok 4.6 standard tier. PROJECTED API-equivalent; individual plans draw from Cursor included/auto quota.", context: 256000),
        ModelRate(provider: "cursor", model: "grok-4.6-fast", input: 4, output: 12, cached: 1, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://cursor.com/docs/models/grok-4-6", status: .estimated, notes: "Internal Cursor cost-rate id for Grok 4.6 Fast mode (2x standard). PROJECTED API-equivalent; not a separate picker model.", context: nil),
        ModelRate(provider: "cursor", model: "grok-4.5", input: 2, output: 6, cached: 0.5, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://cursor.com/docs/models-and-pricing", status: .estimated, notes: "Cursor Grok 4.5 first-party model pool row. PROJECTED API-equivalent; individual plans draw from Cursor included/auto quota.", context: 500000),
        ModelRate(provider: "cursor", model: "cursor-grok-4.5", input: 2, output: 6, cached: 0.5, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://cursor.com/docs/models-and-pricing", status: .estimated, notes: "UI alias for Cursor Grok 4.5. PROJECTED API-equivalent; individual plans draw from Cursor included/auto quota.", context: 500000),
        ModelRate(provider: "codex", model: "gpt-5.6-sol", input: 5, output: 30, cached: 0.5, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://developers.openai.com/api/docs/models/gpt-5.6-sol", status: .estimated, notes: "Codex CLI typically billed via ChatGPT subscription, not per-token.", context: 1050000),
        ModelRate(provider: "codex", model: "gpt-5.6-terra", input: 2.5, output: 15, cached: 0.25, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://developers.openai.com/api/docs/models/gpt-5.6-terra", status: .estimated, notes: nil, context: 1050000),
        ModelRate(provider: "codex", model: "gpt-5.6-luna", input: 1, output: 6, cached: 0.1, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://developers.openai.com/api/docs/models/gpt-5.6-luna", status: .estimated, notes: nil, context: 1050000),
        ModelRate(provider: "codex", model: "gpt-6-astra", input: 10, output: 50, cached: 1, threshold: 272000, longInput: 20, longOutput: 75, longCached: 2, url: "https://developers.openai.com/api/docs/pricing", status: .estimated, notes: "Standard tier; prompts at or above 272K tokens bill every token at the long-context tier. Codex CLI typically billed via ChatGPT subscription, not per-token.", context: 1050000),
        ModelRate(provider: "codex", model: "gpt-6-sol", input: 2, output: 10, cached: 0.2, threshold: 272000, longInput: 4, longOutput: 15, longCached: 0.4, url: "https://developers.openai.com/api/docs/pricing", status: .estimated, notes: "Standard tier; prompts with more than 272K input tokens bill the full request at the long-context tier. Codex CLI typically billed via ChatGPT subscription, not per-token.", context: 1050000),
        ModelRate(provider: "codex", model: "gpt-6-luna", input: 0.1, output: 0.5, cached: 0.01, threshold: 272000, longInput: 0.2, longOutput: 0.75, longCached: 0.02, url: "https://developers.openai.com/api/docs/pricing", status: .estimated, notes: "Standard tier; prompts with more than 272K input tokens bill the full request at the long-context tier. Codex CLI typically billed via ChatGPT subscription, not per-token.", context: 1050000),
        ModelRate(provider: "codex", model: "gpt-5.5", input: 5, output: 30, cached: 0.5, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openai.com/api/pricing", status: .estimated, notes: "Codex CLI typically billed via ChatGPT subscription, not per-token.", context: 1050000),
        ModelRate(provider: "codex", model: "gpt-5.4", input: 2.5, output: 15, cached: 0.25, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openai.com/api/pricing", status: .estimated, notes: nil, context: 1050000),
        ModelRate(provider: "codex", model: "gpt-5.4-mini", input: 0.75, output: 4.5, cached: 0.075, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openai.com/api/pricing", status: .estimated, notes: nil, context: 400000),
        ModelRate(provider: "codex", model: "gpt-5.3-codex", input: 1.5, output: 8, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openai.com/api/pricing", status: .estimated, notes: "Codex-tuned variant; price approximate. Retiring 2026-06-02 per OpenAI (GPT-5.3-Codex-Spark is NOT affected).", context: 400000),
        ModelRate(provider: "codex", model: "gpt-5.3-codex-spark", input: 1.5, output: 8, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openai.com/api/pricing", status: .estimated, notes: "Research preview; pricing may not be public.", context: 200000),
        ModelRate(provider: "codex", model: "gpt-5.2", input: 1, output: 8, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openai.com/api/pricing", status: .estimated, notes: "Retiring 2026-06-02 per OpenAI.", context: 400000),
        ModelRate(provider: "claude", model: "claude-fable-5", input: 10, output: 50, cached: 1, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://platform.claude.com/docs/en/about-claude/models/overview", status: .estimated, notes: "Frontier 1M-context model with adaptive thinking. Published rate $10/$50.", context: 1000000),
        ModelRate(provider: "claude", model: "claude-fable-5-1m", input: 10, output: 50, cached: 1, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.anthropic.com/pricing", status: .estimated, notes: "1M context window at standard rates — no long-context premium published.", context: 1000000),
        ModelRate(provider: "claude", model: "claude-fable-5-1", input: 10, output: 50, cached: 0.25, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://platform.claude.com/docs/en/about-claude/models/overview", status: .estimated, notes: "Current Fable release; successor to Fable 5 at the same $10/$50 per-token rate. Cache reads are $0.25/MTok (0.025x input — a quarter of the Fable 5 rate). 1M context is the default — no -1m variant.", context: 1000000),
        ModelRate(provider: "claude", model: "claude-mythos-5", input: 10, output: 50, cached: 1, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://platform.claude.com/docs/en/about-claude/models/overview", status: .estimated, notes: "Project Glasswing limited-availability 1M-context model with adaptive thinking. Published rate $10/$50.", context: 1000000),
        ModelRate(provider: "claude", model: "claude-opus-5-5", input: 4, output: 20, cached: 0.2, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://platform.claude.com/docs/en/about-claude/pricing", status: .estimated, notes: "Current-gen Opus, released 2026-09-22 at $4/$20 (platform pricing page, read the same day). Cache reads are $0.20/MTok (0.05x input). 1M context is the default — no -1m variant. Fast mode bills 2x ($8/$40) upstream; table keeps the standard tier.", context: 1000000),
        ModelRate(provider: "claude", model: "claude-opus-5", input: 5, output: 25, cached: 0.5, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.anthropic.com/pricing", status: .estimated, notes: "Previous-gen Opus as of Opus 5.5 (2026-09-22); launched 2026-07-24 at Opus 4.8 pricing ($5/$25). 1M context is the default — no -1m variant. Fast mode bills 2x ($10/$50) upstream; table keeps the standard tier.", context: 1000000),
        ModelRate(provider: "claude", model: "claude-opus-4-8", input: 5, output: 25, cached: 0.5, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.anthropic.com/pricing", status: .estimated, notes: "Previous-gen Opus as of Opus 5 (2026-07-24). Published rate $5/$25 (2026-06-09 diligence cycle; replaces the $15/$75 placeholder assumed from the pre-4.5 Opus tier).", context: 200000),
        ModelRate(provider: "claude", model: "claude-opus-4-8-1m", input: 5, output: 25, cached: 0.5, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.anthropic.com/pricing", status: .estimated, notes: "1M context window at standard API pricing — Anthropic dropped the long-context premium from Opus 4.7 onward.", context: 1000000),
        ModelRate(provider: "claude", model: "claude-opus-4-7", input: 5, output: 25, cached: 0.5, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.anthropic.com/pricing", status: .estimated, notes: "Legacy as of Opus 4.8. Published rate $5/$25 (2026-06-09 diligence cycle).", context: 200000),
        ModelRate(provider: "claude", model: "claude-opus-4-7-1m", input: 5, output: 25, cached: 0.5, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.anthropic.com/pricing", status: .estimated, notes: "1M context window at standard API pricing (no long-context premium on 4.7+). Legacy as of Opus 4.8.", context: 1000000),
        ModelRate(provider: "claude", model: "claude-opus-4-6", input: 5, output: 25, cached: 0.5, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.anthropic.com/pricing", status: .estimated, notes: "Previous-gen Opus; same published $5/$25 rate as 4.7/4.8.", context: 200000),
        ModelRate(provider: "claude", model: "claude-sonnet-5", input: 3, output: 15, cached: 0.3, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://platform.claude.com/docs/en/about-claude/models/overview", status: .estimated, notes: "Current-gen Sonnet. Published rate $3/$15 (verified against platform.claude.com 2026-06-30); cached-read at the standard 0.1x input = $0.3. Shares the Opus 4.8 reasoning ladder but Sonnet-tier billing, NOT Opus $5/$25. NOTE: introductory pricing of $2/$10 per MTok applies through 2026-08-31 — the table tracks the standard post-intro rate so historical/forward costs stay correct after the promo ends.", context: 1000000),
        ModelRate(provider: "claude", model: "claude-sonnet-4-6", input: 3, output: 15, cached: 0.3, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.anthropic.com/pricing", status: .estimated, notes: nil, context: 200000),
        ModelRate(provider: "claude", model: "claude-haiku-4-5", input: 1, output: 5, cached: 0.1, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.anthropic.com/pricing", status: .estimated, notes: "Corrected to the published $1/$5 rate (2026-06-09 diligence cycle).", context: 200000),
        ModelRate(provider: "gemini", model: "gemini-3.1-pro-preview", input: 2, output: 12, cached: 0.2, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Historic Gemini CLI/provider tracking row. Gemini is retired for new TaskWraith runs; retained so historical activity estimates remain visible.", context: nil),
        ModelRate(provider: "gemini", model: "gemini-3.1-pro", input: 2, output: 12, cached: 0.2, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Historic plain-id alias priced at Gemini 3.1 Pro Preview standard rates; Gemini is retired for new TaskWraith runs.", context: nil),
        ModelRate(provider: "gemini", model: "gemini-3-flash-preview", input: 0.5, output: 3, cached: 0.05, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Historic Gemini CLI/provider tracking row retained for external activity.", context: nil),
        ModelRate(provider: "gemini", model: "gemini-3.1-flash-lite", input: 0.25, output: 1.5, cached: 0.025, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Historic Gemini CLI/provider tracking row retained for external activity.", context: nil),
        ModelRate(provider: "gemini", model: "gemini-3.1-flash-lite-preview", input: 0.25, output: 1.5, cached: 0.025, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Historic preview alias priced at Gemini 3.1 Flash-Lite standard rates; Gemini is retired for new TaskWraith runs.", context: nil),
        ModelRate(provider: "gemini", model: "gemini-2.5-flash-lite", input: 0.1, output: 0.4, cached: 0.01, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Historic Gemini CLI/provider tracking row retained for external activity.", context: 1048576),
        ModelRate(provider: "kimi", model: "kimi-k2.8-preview", input: 0.95, output: 4, cached: 0.19, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://platform.kimi.ai/docs/pricing/chat-k27-code", status: .estimated, notes: "Current Kimi Code CLI default, on the unchanged `kimi-for-coding` wire id K2.8 Preview took over on 2026-09-11. Moonshot has published no separate K2.8 chat rate, so the K2.7 Coding figures carry forward. PROJECTED API-equivalent for OAuth/subscription runs; automatic context cache hit pricing recorded as cached input.", context: 1048576),
        ModelRate(provider: "kimi", model: "kimi-k2.7-code", input: 0.95, output: 4, cached: 0.19, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://platform.kimi.ai/docs/pricing/chat-k27-code", status: .estimated, notes: "Retired combined \"K2.7 Coding\" row. Kept so usage already recorded under that id still prices instead of falling through to the table head.", context: 262144),
        ModelRate(provider: "kimi", model: "kimi-k2.7-code-highspeed", input: 1.9, output: 8, cached: 0.38, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://platform.kimi.ai/docs/pricing/chat-k27-code", status: .estimated, notes: "Published Highspeed tier, still on K2.7 after the standard route moved to K2.8. Its own picker row since 2026-09-11. PROJECTED API-equivalent for OAuth/subscription runs.", context: 262144),
        ModelRate(provider: "kimi", model: "kimi-k3", input: 3, output: 15, cached: 0.3, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://platform.kimi.ai/docs/pricing/chat-k3", status: .estimated, notes: "Published K3 API pricing for the plan-dependent long-context route. PROJECTED API-equivalent for OAuth/subscription runs.", context: 1048576),
        ModelRate(provider: "kimi", model: "kimi-k3-256k", input: 3, output: 15, cached: 0.3, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://platform.kimi.ai/docs/pricing/chat-k3", status: .estimated, notes: "Same published K3 API pricing for the fixed 256K route. Kimi Code membership documents lower quota consumption than the 1M route; this remains a PROJECTED API-equivalent for subscription runs.", context: 262144),
        ModelRate(provider: "kimi", model: "kimi-k2.6", input: 0.95, output: 4, cached: 0.16, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://platform.kimi.ai/docs/pricing/chat-k26", status: .estimated, notes: "Automatic context cache hit pricing recorded as cached input.", context: 262144),
        ModelRate(provider: "ollama", model: "qwen3:4b-instruct", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Local Ollama model. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "qwen3.5:2b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Qwen 3.5 2B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "qwen3.5:4b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Qwen 3.5 4B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "qwen3.5:9b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Qwen 3.5 9B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "qwen3.6:35b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Qwen 3.6 35B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "qwen3.8:27b-mlx", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Alibaba Qwen 3.8 27B-MLX running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "qwen3.8-flash-next:125b-mlx", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Alibaba Qwen 3.8 Flash Next 125B-MLX running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "gemma3:4b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Google Gemma 3 4B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "gemma4:12b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Google Gemma 4 12B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "gemma4:31b-mlx", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Google Gemma 4 31B-MLX running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "ornith", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Ornith 1.0 9B alias running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "ornith:latest", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Ornith 1.0 9B alias running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "ornith:9b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Ornith 1.0 9B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "ornith:35b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Ornith 1.0 35B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "ornith-1.5:9b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Ornith 1.5 9B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "ornith-1.5:35b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Ornith 1.5 35B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "laguna-xs-2.1:q8_0", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Poolside Laguna XS 2.1 Q8 running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "gemma4:12b-it-q4_k_m", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Google Gemma 4 12B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "gpt-oss", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "OpenAI gpt-oss 20B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "gpt-oss:20b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "OpenAI gpt-oss 20B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "gpt-oss:latest", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "OpenAI gpt-oss 20B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "minicpm-v4.5:8b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "MiniCPM-V 4.5 8B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "granite4:3b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "IBM Granite 4.0 3B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "granite4.1:3b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "IBM Granite 4.1 3B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "granite4.1:30b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "IBM Granite 4.1 30B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "granite4.2:3b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "IBM Granite 4.2 3B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "granite4.2:8b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "IBM Granite 4.2 8B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "granite4.2:30b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "IBM Granite 4.2 30B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "nemotron-3-nano:4b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "NVIDIA Nemotron 3 Nano 4B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "nemotron3:33b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "NVIDIA Nemotron 3 Nano Omni 33B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "nemotron-3.5-lightning:30b-mlx", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "NVIDIA Nemotron 3.5 Lightning 30B-MLX running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "lfm2.5-thinking:1.2b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Liquid LFM 2.5 Thinking 1.2B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "lfm2.5:8b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Liquid LFM 2.5 8B-A1B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "openai/gpt-oss-20b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "OpenAI gpt-oss 20B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "devstral-small-2:24b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Mistral Devstral Small 2 24B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "mistral-medium-3.5:128b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Mistral Medium 3.5 128B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "ministral-3:3b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Mistral Ministral 3 3B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "ministral-3:14b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Mistral Ministral 3 14B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "muse-glimmer:30b-mlx", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Meta Muse Glimmer 30B-MLX running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "llama3.1:8b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Meta Llama 3.1 8B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "deepseek-r1:1.5b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "DeepSeek R1 Distill Qwen 1.5B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "deepseek-r1:8b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "DeepSeek R1 8B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "rnj-1", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Essential AI Rnj-1 8B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "glm-4.7-flash:q4_k_m", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Z.ai GLM-4.7-Flash 30B-A3B Q4 running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "north-mini-code-1.0:q4_k_m", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Cohere North Mini Code 1.0 30B-A3B Q4 running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "ollama", model: "llama3.2:3b", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "local://ollama", status: .estimated, notes: "Meta Llama 3.2 3B running through local Ollama. TaskWraith does not charge per token for local inference.", context: nil),
        ModelRate(provider: "pi", model: "deepseek/deepseek-v4-flash", input: 0.3, output: 1.2, cached: 0.006, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://api-docs.deepseek.com/quick_start/pricing", status: .estimated, notes: "Pi default model (DeepSeek API direct). First row = fallback rate for unknown pi ids. PEAK figures. DeepSeek bills peak 01:00-04:00 and 06:00-10:00 UTC Mon-Fri and half that off-peak ($0.15 / $0.60 / $0.003 cached), which this flat table cannot express; peak is carried so a projection never understates a bill. Re-verified 2026-09-10: DeepSeek released V4.1 Flash on 2026-09-10 under the new id `deepseek-flash` and now routes the legacy `deepseek-v4-flash` id to it at V4.1 Flash prices, so this row prices V4.1 Flash. The old V4 Flash figures ($0.14 / $0.28) are gone from the vendor page; pi 0.84.2 and 0.85.1 both still ship the stale $0.14 / $0.28 cost block, so do NOT re-sync this row from pi bundled data.", context: 1000000),
        ModelRate(provider: "pi", model: "deepseek/deepseek-v4-pro", input: 1.32, output: 3.96, cached: 0.044, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://api-docs.deepseek.com/quick_start/pricing", status: .estimated, notes: "DeepSeek V4 Pro via the Pi seat. PEAK figures, same window as the flash row above; off-peak is half ($0.66 / $1.98 / $0.022 cached). Re-verified 2026-09-10 against the vendor page. The previous $0.435 / $0.87 came from pi bundled data (`pi-ai/dist/providers/data/deepseek.json`), which disagrees with DeepSeek own published pricing and is still wrong in pi 0.85.1 - price this row from the vendor page, never from pi. SCHEDULED CHANGE: from 12:00 Beijing / 04:00 UTC on 2026-09-14, and until a future V4.1 Pro ships, DeepSeek routes every `deepseek-v4-pro` request to V4.1 Flash and bills at V4.1 Flash prices, so on that date this row should drop to the flash figures above. The flat table cannot express a dated change; this records it the way the gemini-3.6-flash row records its own.", context: 1000000),
        ModelRate(provider: "pi", model: "zai/glm-4.7", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.z.ai/guides/overview/pricing", status: .subscription, notes: "Z.ai coding-plan lane — subscription, no per-token rate published.", context: 204800),
        ModelRate(provider: "pi", model: "zai/glm-5.1", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.z.ai/guides/overview/pricing", status: .subscription, notes: "Z.ai coding-plan lane — subscription, no per-token rate published.", context: 200000),
        ModelRate(provider: "pi", model: "zai/glm-5.2", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.z.ai/guides/overview/pricing", status: .subscription, notes: "Z.ai coding-plan lane — subscription, no per-token rate published.", context: 1000000),
        ModelRate(provider: "pi", model: "qwen-token-plan/qwen3.7-max", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://pi.dev/docs/latest/providers", status: .subscription, notes: "Qwen token plan — prepaid allowance, no per-token rate published.", context: 1000000),
        ModelRate(provider: "pi", model: "qwen-token-plan/qwen3.7-plus", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://pi.dev/docs/latest/providers", status: .subscription, notes: "Qwen token plan — prepaid allowance, no per-token rate published.", context: 1000000),
        ModelRate(provider: "pi", model: "qwen-token-plan/qwen3.8-max", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://pi.dev/docs/latest/providers", status: .subscription, notes: "Qwen token plan — prepaid allowance, no per-token rate published.", context: 1000000),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-cn/mimo-v2-pro", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://pi.dev/docs/latest/providers", status: .subscription, notes: "Xiaomi token plan (China) — prepaid allowance, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-cn/mimo-v2.5", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://pi.dev/docs/latest/providers", status: .subscription, notes: "Xiaomi token plan (China) — prepaid allowance, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-cn/mimo-v2.5-pro", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://pi.dev/docs/latest/providers", status: .subscription, notes: "Xiaomi token plan (China) — prepaid allowance, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-cn/mimo-v2.6-pro", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mimo.mi.com/docs/en-US/price/token-plan", status: .subscription, notes: "Xiaomi token plan (China) — prepaid credits, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-cn/mimo-v2.6-flash", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mimo.mi.com/docs/en-US/price/token-plan", status: .subscription, notes: "Xiaomi token plan (China) — prepaid credits, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-sgp/mimo-v2-pro", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://pi.dev/docs/latest/providers", status: .subscription, notes: "Xiaomi token plan (Singapore) — prepaid allowance, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-sgp/mimo-v2.5", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://pi.dev/docs/latest/providers", status: .subscription, notes: "Xiaomi token plan (Singapore) — prepaid allowance, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-sgp/mimo-v2.5-pro", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://pi.dev/docs/latest/providers", status: .subscription, notes: "Xiaomi token plan (Singapore) — prepaid allowance, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-sgp/mimo-v2.6-pro", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mimo.mi.com/docs/en-US/price/token-plan", status: .subscription, notes: "Xiaomi token plan (Singapore) — prepaid credits, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-sgp/mimo-v2.6-flash", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mimo.mi.com/docs/en-US/price/token-plan", status: .subscription, notes: "Xiaomi token plan (Singapore) — prepaid credits, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-ams/mimo-v2-pro", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://pi.dev/docs/latest/providers", status: .subscription, notes: "Xiaomi token plan (Amsterdam) — prepaid allowance, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-ams/mimo-v2.5", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://pi.dev/docs/latest/providers", status: .subscription, notes: "Xiaomi token plan (Amsterdam) — prepaid allowance, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-ams/mimo-v2.5-pro", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://pi.dev/docs/latest/providers", status: .subscription, notes: "Xiaomi token plan (Amsterdam) — prepaid allowance, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-ams/mimo-v2.6-pro", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mimo.mi.com/docs/en-US/price/token-plan", status: .subscription, notes: "Xiaomi token plan (Amsterdam) — prepaid credits, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "xiaomi-token-plan-ams/mimo-v2.6-flash", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mimo.mi.com/docs/en-US/price/token-plan", status: .subscription, notes: "Xiaomi token plan (Amsterdam) — prepaid credits, no per-token rate published.", context: 1048576),
        ModelRate(provider: "pi", model: "minimax/minimax-m2.7", input: 0.3, output: 1.2, cached: 0.06, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://platform.minimax.io/docs/price", status: .estimated, notes: "MiniMax model ids are CASE-SENSITIVE.", context: 204800),
        ModelRate(provider: "pi", model: "minimax/minimax-m3", input: 0.3, output: 1.2, cached: 0.06, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://platform.minimax.io/docs/price", status: .estimated, notes: "MiniMax model ids are CASE-SENSITIVE.", context: 1000000),
        ModelRate(provider: "pi", model: "mistral/zai-glm-5-2", input: 1.4, output: 4.4, cached: 0.14, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/zai-glm-5-2", status: .estimated, notes: "Third-party Z.ai GLM-5.2 served without modification by Mistral.", context: 1000000),
        ModelRate(provider: "pi", model: "mistral/mistral-medium-3.5", input: 1.5, output: 7.5, cached: 0.15, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mistral.ai/pricing", status: .estimated, notes: nil, context: 262144),
        ModelRate(provider: "pi", model: "mistral/mistral-medium-latest", input: 1.5, output: 7.5, cached: 0.15, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mistral.ai/pricing", status: .estimated, notes: "Floating Mistral Medium alias; currently priced like Mistral Medium 3.5.", context: 262144),
        ModelRate(provider: "pi", model: "mistral/mistral-small-2603", input: 0.15, output: 0.6, cached: 0.015, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/mistral-small-4-0-26-03", status: .estimated, notes: nil, context: 256000),
        ModelRate(provider: "pi", model: "mistral/mistral-large-2512", input: 0.5, output: 1.5, cached: 0.05, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mistral.ai/pricing", status: .estimated, notes: "Mistral Large 3. Cheaper per token than medium-3.5 despite being the flagship — do not infer this row from the medium one.", context: 262144),
        ModelRate(provider: "pi", model: "mistral/devstral-2512", input: 0.4, output: 2, cached: 0.04, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mistral.ai/pricing", status: .estimated, notes: nil, context: 262144),
        ModelRate(provider: "pi", model: "mistral/codestral-2508", input: 0.3, output: 0.9, cached: 0.03, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/codestral-25-08", status: .estimated, notes: nil, context: 131072),
        ModelRate(provider: "pi", model: "mistral/labs-leanstral-1-5", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/leanstral-1-5", status: .free, notes: "Free Mistral Labs public preview; Labs ids may change on short notice.", context: 262144),
        ModelRate(provider: "pi", model: "mistral/mistral-medium-2508", input: 0.4, output: 2, cached: 0.04, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mistral.ai/pricing", status: .estimated, notes: nil, context: 262144),
        ModelRate(provider: "pi", model: "mistral/mistral-medium-2505", input: 0.4, output: 2, cached: 0.04, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mistral.ai/pricing", status: .estimated, notes: nil, context: 131072),
        ModelRate(provider: "pi", model: "mistral/ministral-14b-2512", input: 0.2, output: 0.2, cached: 0.02, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/ministral-3-14b-25-12", status: .estimated, notes: nil, context: 262144),
        ModelRate(provider: "pi", model: "mistral/ministral-8b-2512", input: 0.15, output: 0.15, cached: 0.015, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/ministral-3-8b-25-12", status: .estimated, notes: nil, context: 262144),
        ModelRate(provider: "pi", model: "mistral/ministral-3b-2512", input: 0.1, output: 0.1, cached: 0.01, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/ministral-3-3b-25-12", status: .estimated, notes: nil, context: 262144),
        ModelRate(provider: "pi", model: "groq/openai/gpt-oss-120b", input: 0.15, output: 0.6, cached: 0.075, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://groq.com/pricing", status: .estimated, notes: "Paid tier; Groq also has a free tier where actual spend is 0.", context: 131072),
        ModelRate(provider: "pi", model: "groq/qwen/qwen3-32b", input: 0.29, output: 0.59, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://groq.com/pricing", status: .estimated, notes: "Paid tier; Groq also has a free tier where actual spend is 0.", context: 131072),
        ModelRate(provider: "pi", model: "cerebras/gpt-oss-120b", input: 0.35, output: 0.75, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.cerebras.ai/pricing", status: .estimated, notes: "Paid tier; Cerebras also has a free 1M tokens/day tier.", context: 131072),
        ModelRate(provider: "pi", model: "cerebras/qwen-3.8-27b", input: 0.99, output: 1.49, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.cerebras.ai/pricing", status: .estimated, notes: "Listed on the Cerebras Developer Tier pricing table (~1,500 tokens/s); ~2.8x the gpt-oss-120b input rate.", context: 131072),
        ModelRate(provider: "pi", model: "cerebras/zai-glm-4.7", input: 2.25, output: 2.75, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.cerebras.ai/pricing", status: .estimated, notes: "Most expensive wired Pi model by input rate — ~16x DeepSeek V4 Flash.", context: 131072),
        ModelRate(provider: "pi", model: "openrouter/stealth/ox-alpha", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/stealth/ox-alpha", status: .free, notes: "Formerly free on OpenRouter; retired 2026-08-28 and retained only so historical Pi chats and ensemble seats keep their cost records.", context: 1048576),
        ModelRate(provider: "pi", model: "openrouter/z-ai/glm-5.2", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/z-ai/glm-5.2", status: .free, notes: "Free on OpenRouter (verified 2026-08-21); mirrors cost 0/0 in PiOpenRouterModelRegistration.", context: 256000),
        ModelRate(provider: "pi", model: "openrouter/poolside/laguna-s-2.1", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/poolside/laguna-s-2.1", status: .free, notes: "Free on OpenRouter (verified 2026-08-21); mirrors cost 0/0 in PiOpenRouterModelRegistration.", context: 256000),
        ModelRate(provider: "pi", model: "openrouter/nvidia/nemotron-3-ultra-550b-a55b:free", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/nvidia/nemotron-3-ultra-550b-a55b:free", status: .free, notes: "OpenRouter :free variant (verified 2026-08-21); mirrors cost 0/0 in PiOpenRouterModelRegistration.", context: 1000000),
        ModelRate(provider: "pi", model: "openrouter/cohere/north-mini-code:free", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/cohere/north-mini-code:free", status: .free, notes: "OpenRouter :free variant (verified 2026-08-30); mirrors cost 0/0 in PiOpenRouterModelRegistration.", context: 256000),
        ModelRate(provider: "pi", model: "openrouter/minimax/minimax-m3:free", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/minimax/minimax-m3:free", status: .free, notes: "OpenRouter :free variant (verified 2026-08-30); mirrors cost 0/0 in PiOpenRouterModelRegistration.", context: 1048576),
        ModelRate(provider: "pi", model: "openrouter/thinkingmachines/inkling:free", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/thinkingmachines/inkling:free", status: .free, notes: "OpenRouter :free variant (verified 2026-08-30); mirrors cost 0/0 in PiOpenRouterModelRegistration.", context: 1048576),
        ModelRate(provider: "pi", model: "openrouter/thinkingmachines/inkling-small:free", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/thinkingmachines/inkling-small:free", status: .free, notes: "OpenRouter :free variant (verified 2026-08-30); mirrors cost 0/0 in PiOpenRouterModelRegistration.", context: 1048576),
        ModelRate(provider: "pi", model: "openrouter/tencent/hy4-preview", input: 0.834, output: 2.501, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/tencent/hy4-preview", status: .estimated, notes: "Paid OpenRouter route (verified 2026-09-09); mirrors the cost block in PiOpenRouterModelRegistration.", context: 1048576),
        ModelRate(provider: "pi", model: "openrouter/inception/mercury-2.5-preview", input: 0.2, output: 0.75, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/inception/mercury-2.5-preview", status: .estimated, notes: "Paid OpenRouter route (verified 2026-09-09); mirrors the cost block in PiOpenRouterModelRegistration.", context: 260000),
        ModelRate(provider: "pi", model: "openrouter/inception/mercury-2.5", input: 0.2, output: 0.75, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/inception/mercury-2.5", status: .estimated, notes: "List price (verified 2026-09-09). OpenRouter is discounting the launch 80% to $0.04/$0.15; the estimate tracks the list rate so it does not under-bill when that promotion ends.", context: 260000),
        ModelRate(provider: "pi", model: "openrouter/nex-agi/nex-n2.5-mini:free", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/nex-agi/nex-n2.5-mini:free", status: .free, notes: "OpenRouter :free variant (verified 2026-09-09); mirrors cost 0/0 in PiOpenRouterModelRegistration.", context: 262144),
        ModelRate(provider: "pi", model: "openrouter/nex-agi/nex-n2.5-pro:free", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/nex-agi/nex-n2.5-pro:free", status: .free, notes: "OpenRouter :free variant (verified 2026-09-09); mirrors cost 0/0 in PiOpenRouterModelRegistration.", context: 262144),
        ModelRate(provider: "pi", model: "openrouter/sakana/fugu-max", input: 2, output: 6, cached: 0.25, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/sakana/fugu-max", status: .estimated, notes: "Paid OpenRouter route, Sakana-hosted with no routing fan-out (verified 2026-09-11); mirrors the cost block in PiOpenRouterModelRegistration. Web search is billed separately at $10 per 1K calls and is not part of a token estimate.", context: 1000000),
        ModelRate(provider: "pi", model: "openrouter/sakana/fugu-ultra-v2", input: 5, output: 30, cached: 0.5, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/sakana/fugu-ultra-v2", status: .estimated, notes: "Paid OpenRouter route (verified 2026-09-11). BASE tier: OpenRouter publishes a pricing override that raises this to $10 / $45 with $1.00 cache read once the PROMPT exceeds 272,000 tokens. This flat table cannot express a prompt-length break, so a long-prompt turn is UNDER-estimated by up to 2x on input and 1.5x on output; the break is recorded in docs/MODEL_CATALOGUE.md.", context: 1000000),
        ModelRate(provider: "pi", model: "openrouter/stealth/union-alpha", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/stealth/union-alpha", status: .free, notes: "Free stealth preview (verified 2026-09-16); mirrors cost 0/0 in PiOpenRouterModelRegistration. Free for the duration of the preview only — if the route is ever relisted at a price this row must be re-verified before it prices another run.", context: 262144),
        ModelRate(provider: "pi", model: "openrouter/unbiased/pareto", input: 2.5, output: 7.5, cached: 0.25, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/unbiased/pareto", status: .estimated, notes: "Paid OpenRouter route, Unbiased-hosted with no routing fan-out (verified 2026-09-18); mirrors the cost block in PiOpenRouterModelRegistration.", context: 262144),
        ModelRate(provider: "pi", model: "openrouter/typesafe/jev-1.13", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/typesafe/jev-1.13", status: .pending, notes: "Route listed 2026-09-17 but \"coming soon\" — OpenRouter publishes no pricing yet. Zero is a neutral placeholder, NOT a free-route claim: re-verify against the Models API at launch before it prices a run.", context: 32000),
        ModelRate(provider: "pi", model: "openrouter/stealth/space-bunny-alpha", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://openrouter.ai/stealth/space-bunny-alpha", status: .free, notes: "Free stealth preview (verified 2026-09-23); mirrors cost 0/0 in PiOpenRouterModelRegistration. Free for the duration of the preview only — if the route is ever relisted at a price this row must be re-verified before it prices another run.", context: 1000000),
        ModelRate(provider: "antigravity", model: "gemini-api:gemini-2.5-flash", input: 0.3, output: 2.5, cached: 0.03, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Gemini API paid tier via the AntiGravity BYO-key lane. First row = fallback rate for unknown/agy ids.", context: 1048576),
        ModelRate(provider: "antigravity", model: "gemini-api:gemini-2.5-flash-lite", input: 0.1, output: 0.4, cached: 0.01, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Gemini API paid tier via the AntiGravity BYO-key lane.", context: 1048576),
        ModelRate(provider: "antigravity", model: "gemini-api:gemini-2.5-pro", input: 1.25, output: 10, cached: 0.125, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Gemini API paid tier, ≤200K-prompt rate; >200K prompts bill higher (not modelled — long-prompt estimates undercount).", context: 1048576),
        ModelRate(provider: "antigravity", model: "gemini-api:gemini-3.1-pro", input: 2, output: 12, cached: 0.2, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Gemini API paid tier via the AntiGravity BYO-key lane. Covers the -preview alias by prefix.", context: nil),
        ModelRate(provider: "antigravity", model: "gemini-api:gemini-3.1-flash-lite", input: 0.25, output: 1.5, cached: 0.025, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Gemini API paid tier via the AntiGravity BYO-key lane.", context: nil),
        ModelRate(provider: "antigravity", model: "gemini-api:gemini-2.0-flash", input: 0.1, output: 0.4, cached: 0.025, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Gemini API paid tier via the AntiGravity BYO-key lane.", context: 1048576),
        ModelRate(provider: "antigravity", model: "gemini-api:gemini-3.6-flash", input: 0.75, output: 3.75, cached: 0.075, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Gemini API paid tier via the AntiGravity BYO-key lane. Promotional rate through 2026-12-31; doubles 2027-01-01.", context: nil),
        ModelRate(provider: "antigravity", model: "gemini-api:gemini-3.5-flash", input: 1.5, output: 9, cached: 0.15, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Gemini API paid tier via the AntiGravity BYO-key lane.", context: nil),
        ModelRate(provider: "antigravity", model: "gemini-api:gemini-3.1-pro-preview", input: 2, output: 12, cached: 0.2, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://ai.google.dev/gemini-api/docs/pricing", status: .estimated, notes: "Gemini API paid tier, ≤200K-prompt rate; >200K prompts bill higher (not modelled — long-prompt estimates undercount).", context: nil),
        ModelRate(provider: "mistral", model: "mistral-medium-3.5", input: 1.5, output: 7.5, cached: 0.15, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mistral.ai/pricing", status: .estimated, notes: "Vibe CLI default model. PROJECTED API-equivalent for the plan-backed subscription lane, not actual billing. First row = fallback rate for unknown mistral ids. Cached-input 0.15 is the cached_input_price in the Vibe CLI's own bundled catalogue (vibe/core/config/vibe_schema.py, since 2.24.1) and matches docs.mistral.ai/inference/pricing; the marketing page quotes no cache rate.", context: 262144),
        ModelRate(provider: "mistral", model: "mistral-vibe-cli-latest", input: 1.5, output: 7.5, cached: 0.15, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mistral.ai/pricing", status: .estimated, notes: "Wire id alias for mistral-medium-3.5 — some Vibe CLI events report this id instead of the display name.", context: 262144),
        ModelRate(provider: "mistral", model: "devstral-small", input: 0.1, output: 0.3, cached: 0.01, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mistral.ai/pricing", status: .estimated, notes: "Read from the Vibe CLI's own bundled catalog (vibe/core/config/vibe_schema.py DEFAULT_MODELS: devstral-small-latest, input_price=0.1, output_price=0.3, cached_input_price=0.01 in 2.24.1-2.24.5; 2.25.0 dropped the model), which is authoritative over the marketing page. Do NOT copy the $0.40/$2.00 figure — that is Devstral 2, a DIFFERENT and larger model from Devstral 2 Small. PROJECTED API-equivalent for the plan-backed subscription lane, not actual billing.", context: 262144),
        ModelRate(provider: "mistral", model: "mistral-large-2512", input: 0.5, output: 1.5, cached: 0.05, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mistral.ai/pricing", status: .estimated, notes: "Mistral Large 3.", context: 262144),
        ModelRate(provider: "mistral", model: "zai-glm-5-2", input: 1.4, output: 4.4, cached: 0.14, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/zai-glm-5-2", status: .estimated, notes: "Third-party Z.ai GLM-5.2 served by Mistral.", context: 1000000),
        ModelRate(provider: "mistral", model: "zai-glm-5-3", input: 1.4, output: 4.4, cached: 0.14, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/zai-glm-5-2", status: .estimated, notes: "Third-party Z.ai GLM-5.3 served by Mistral, added 2026-09-18. CARRIED FORWARD from the GLM-5.2 row above: Mistral has published no separate GLM-5.3 rate, and Z.ai prices its own GLM-5.3 identically to 5.2 (see devinModelCatalog, 1.4/4.4). The cached-input figure is 5.2's Mistral-docs 0.14, not Z.ai's own 0.26. Re-verify against Mistral's model docs when the 5.3 page lands — every offered model must carry a rate row (providerApiRatesTable guard), so this is a sourced-adjacent estimate rather than an omission.", context: 1000000),
        ModelRate(provider: "mistral", model: "glm-5-2", input: 1.4, output: 4.4, cached: 0.26, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/zai-glm-5-2", status: .estimated, notes: "GLM-5.2 hosted on the Vibe subscription (alias glm-5-2, same zai-glm-5-2 deployment as the API row above). Cached-input 0.26 read from the Vibe CLI's own bundled catalogue (vibe_cli_extra_models), authoritative over the marketing page; the API row above quotes the docs' 0.14. PROJECTED API-equivalent for the plan-backed subscription lane, not actual billing.", context: 1000000),
        ModelRate(provider: "mistral", model: "glm-5-3", input: 1.4, output: 4.4, cached: 0.26, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/zai-glm-5-2", status: .estimated, notes: "GLM-5.3 hosted on the Vibe subscription (alias glm-5-3, added 2026-09-21). Rate CARRIED FORWARD from the 5.2 deployment (same 1.4/4.4, 0.26 cache read) and not independently verified. PROJECTED API-equivalent for the plan-backed subscription lane, not actual billing.", context: 1000000),
        ModelRate(provider: "mistral", model: "codestral-2508", input: 0.3, output: 0.9, cached: 0.03, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/codestral-25-08", status: .estimated, notes: nil, context: 131072),
        ModelRate(provider: "mistral", model: "mistral-small-2603", input: 0.15, output: 0.6, cached: 0.015, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/mistral-small-4-0-26-03", status: .estimated, notes: nil, context: 256000),
        ModelRate(provider: "mistral", model: "devstral-2512", input: 0.4, output: 2, cached: 0.04, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mistral.ai/pricing", status: .estimated, notes: nil, context: 262144),
        ModelRate(provider: "mistral", model: "labs-leanstral-1-5", input: 0, output: 0, cached: nil, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/leanstral-1-5", status: .free, notes: "Free Mistral Labs public preview.", context: 262144),
        ModelRate(provider: "mistral", model: "mistral-medium-latest", input: 1.5, output: 7.5, cached: 0.15, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mistral.ai/pricing", status: .estimated, notes: nil, context: 262144),
        ModelRate(provider: "mistral", model: "mistral-medium-2508", input: 0.4, output: 2, cached: 0.04, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mistral.ai/pricing", status: .estimated, notes: nil, context: 262144),
        ModelRate(provider: "mistral", model: "mistral-medium-2505", input: 0.4, output: 2, cached: 0.04, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://mistral.ai/pricing", status: .estimated, notes: nil, context: 131072),
        ModelRate(provider: "mistral", model: "ministral-14b-2512", input: 0.2, output: 0.2, cached: 0.02, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/ministral-3-14b-25-12", status: .estimated, notes: nil, context: 262144),
        ModelRate(provider: "mistral", model: "ministral-8b-2512", input: 0.15, output: 0.15, cached: 0.015, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/ministral-3-8b-25-12", status: .estimated, notes: nil, context: 262144),
        ModelRate(provider: "mistral", model: "ministral-3b-2512", input: 0.1, output: 0.1, cached: 0.01, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://docs.mistral.ai/models/ministral-3-3b-25-12", status: .estimated, notes: nil, context: 262144),
        ModelRate(provider: "muse", model: "muse-spark-1.2", input: 1.25, output: 4.25, cached: 0.15, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.meta.com/", status: .estimated, notes: "PROJECTED API-equivalent from the Muse Code CLI catalog for muse-spark-1.2 ($1.25/$4.25/$0.15 per Mtok input/output/cached). Not Meta-billed invoice line items — subscription / plan spend may differ.", context: 200000),
        ModelRate(provider: "muse", model: "muse-spark-1.2-contributor", input: 0.1, output: 0.2, cached: 0.002, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.meta.com/", status: .estimated, notes: "PROJECTED API-equivalent from the Muse Code CLI catalog for muse-spark-1.2-contributor ($0.10/$0.20/$0.002 per Mtok input/output/cached). Discounted tokens carry the provider notice that content, including inter-session messages, may be used for product improvement. Not Meta-billed invoice line items — subscription / plan spend may differ.", context: 200000),
        ModelRate(provider: "muse", model: "muse-default", input: 1.25, output: 4.25, cached: 0.15, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://www.meta.com/", status: .estimated, notes: "Wire-id alias for muse-spark-1.2 when a run records the seat default sentinel instead of the catalog id.", context: nil),
        ModelRate(provider: "muse", model: "muse-spark-1.3", input: 1.25, output: 4.25, cached: 0.15, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://developer.meta.com/ai/products/meta-model-api/", status: .estimated, notes: "Meta Model API published pricing for muse-spark-1.3 ($1.25/$4.25/$0.15 per Mtok input/output/cached), verified 2026-09-02 and identical to muse-spark-1.2. Not Meta-billed invoice line items — subscription / plan spend may differ.", context: 200000),
        ModelRate(provider: "muse", model: "muse-spark-1.3-contributor", input: 0.1, output: 0.2, cached: 0.002, threshold: nil, longInput: nil, longOutput: nil, longCached: nil, url: "https://developer.meta.com/ai/products/meta-model-api/", status: .estimated, notes: "Meta Model API published pricing for muse-spark-1.3-contributor ($0.10/$0.20/$0.002 per Mtok input/output/cached), verified 2026-09-02. Discounted tokens carry the provider notice that content, including inter-session messages, may be used for product improvement. Not Meta-billed invoice line items — subscription / plan spend may differ.", context: 200000),
    ]
}
